name: Build and Test Project
run-name: Build and test last commit by @${{ github.actor }}
on:
  pull_request:
jobs:
  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    concurrency: 
      group: unity-build
      cancel-in-progress: true
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
   
      # Cache
      - name: Cache project
        uses: actions/cache@v4
        with:
          path: ../../Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
            
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          buildName: ${{ matrix.targetPlatform }}Build-${{ github.run_number }}-${{ github.run_id }}
        
      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build

